### Evaluate resume against job description, both as files
POST http://localhost:8080/api/v1/evaluations/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="resume"; filename="TestCV2.pdf"
Content-Type: application/pdf

< ./test-files/TestCV2.pdf
--WebAppBoundary
Content-Disposition: form-data; name="jobDescription"; filename="vacancy-poz.txt"
Content-Type: text/plain

< ./test-files/vacancy-poz.txt
--WebAppBoundary--