spring:
  application:
    name: resume-evaluator

  ai:
    retry:
      max-attempts: 1
    openai:
      api-key: ${OPENAI_API_KEY}

      chat:
        options:
          model: gpt-4o
          temperature: 0.0
          max-tokens: 1500

  spring:
    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 10MB